version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    volumes:
      - db:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "suchSecureVeryWordSoPassW0w!"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
volumes:
  db:
    name: swabe-lesson-11-db